version: 2.1

orbs:
  python: circleci/python@2.0.3

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: "3.7"
    steps:
      - checkout

      - run:
          name: Set up Virtual Environment
          command: |
            python -m venv env
            source env/bin/activate

      - run:
          name: Install Dependencies
          command: |
            source env/bin/activate
            pip install -r requirements.txt

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - cicd-demo
